language: python
python:
  - "2.6"
  - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get install -qq thrift-compiler
  - which thrift
  - pip install markerlib
before_script:
  - sudo sh -c "echo \"Asia/Seoul\" > /etc/timezone"
  - export TZ=Asia/Seoul
  - date
  - cp etc/arara_settings.py.sample etc/arara_settings.py
  - make
script: py.test arara/test
notifications:
  email:
    - arara@sparcs.org
  irc:
    - "irc.ozinger.org#sparcs"
